# Action that creates a new release
# See make release for details
name: Release

permissions:
  contents: write

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      # See https://github.com/3box/rust-builder
      image: public.ecr.aws/r5b3e0r5/3box/rust-builder:latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      # Image uses a custom user and it needs to own the workspace directory
      # Note use of sudo to allow ownership change.
      - name: Chown workspace to user
        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git config user.email "github@3box.io"
          git config user.name "Github Automation"
      - name: Perform release
        run: make release
