# Action that creates a new release
# See make release for details
name: Release

permissions:
  contents: write

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      # See https://github.com/3box/rust-builder
      image: public.ecr.aws/r5b3e0r5/3box/rust-builder:latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Perform release
        run: make release
